### ISSUE TITLE
dzdb access request form

### ISSUE THREAD

**Issue by bhuffaker** [CAIDA/dzdb-web#15]
Please create a dzdb data access form
- You can mode it after https://www.caida.org/data/request_user_info_forms/as_relationships.xml
- it should send email to dzdb-info@caida.org 

- [ ] email the form's email to Nicole Lee <nicolemandylee8@gmail.com>  , so she can update the catalog entry

**Comment by amacaida** [comment]
* Is this called the DZDB Dataset?
* dzdb-info@caida.org sends to nicole and who else? it shouldn't be only an REU

**Comment by bhuffaker** [comment]
> On Jan 15, 2021, at 12:46 PM, Alex Ma <notifications@github.com> wrote:
> 
> 
> Is this called the DZDB Dataset?
> dzdb-info@caida.org <mailto:dzdb-info@caida.org> sends to nicole and who else? it shouldn't be only an REU

This is going to be the API https://catalog.caida.org/details/software/dzdb_api

**Comment by amacaida** [comment]
What happens when the form is submitted? the AS Relationships one redirects the user to http://data.caida.org/datasets/as-relationships/

**Comment by bhuffaker** [comment]
It should send an email to the mailing list and a webpage letting them know it was processed.  Whatever the current forms that do not go straight to the data say.

**Comment by amacaida** [comment]
Do you want it to also send to public-data-access@caida.org or like other datasets?

**Comment by amacaida** [comment]
Draft looks like https://www-xml.caida.org/~macat/data/request_user_info_forms/dzdb.xml

**Comment by bhuffaker** [comment]
Do all the pages share the same page?

	https://www.caida.org/cgi-bin/FormHandler/FormHandler.cgi <https://www.caida.org/cgi-bin/FormHandler/FormHandler.cgi>

**Comment by amacaida** [comment]
Yes they all point to the same formhandler script which reads different configuration files depending on the hidden values passed to it.  The data-request ones generically send to public-data-access@caida.org, but I can write an if type==dzdb then either cc dzdb-info@ in addition to public-data-access@, or email dzdb-info instead of public-data-access, just need to know how you want it.

**Comment by bhuffaker** [comment]
looks good make it live
- if possible add a link to https://catalog.caida.org/details/software/dzdb_api

**Comment by amacaida** [comment]
Ok then on submission it will email public-data-access@caida.org cc dzdb-info

**Comment by bhuffaker** [comment]
What is the URL going to be?

**Comment by amacaida** [comment]
https://www.caida.org/data/request_user_info_forms/dzdb.xml
