### ISSUE TITLE
create search results page

### ISSUE THREAD

**Issue by lanrat** [CAIDA/dzdb-web#33]
when using the main search box and you get 0 results it does not show you the search page.

Currently it just reloads the page. This is confusing. Better feedback should be provided to the user.

**Comment by ryankoga** [comment]
This bug isn't currently in dzdb, but is in dnscoffee.  https://github.com/lanrat/dnscoffee/commit/b9f1d8fa352a5023b37f1c3fe614b43e3f39f926 changes the default to a reload but doesn't change the navbar search to have a default type of "_".  So the fix should just be to add that default after merging changes.

**Comment by lanrat** [comment]
Good find! Thanks for investigating.

**Comment by lanrat** [comment]
@ryankoga did my bad commit that is causing this bug end up getting merged into DZDB? I'm now seeing the same behavior on both sites.

**Comment by ryankoga** [comment]
Hah oh yeah I should just fix that.
